[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Felipe Baltor <fbaltor@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.65.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
