version: "3.7"

networks:
  common-network:
    driver: bridge

services:
  api:
    # Named containers must be used to stay synchronized with the database host
    # address.
    container_name: api
    build:
      context: ./api
    ports:
      - 8000:8000
    networks:
      - common-network
    environment:
      PORT: 8000
    volumes:
      - ./api/app:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000","--debug", "--reload-dir", "/app"]

  auth-server:
    image: quay.io/keycloak/keycloak:latest
    container_name: auth-server
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      DB_VENDOR: postgres
      DB_ADDR: auth-db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_SCHEMA: public
    ports:
      - 8080:8080
    depends_on:
      - auth-db
    networks:
      - common-network 
    volumes:
      - ./auth-server/tmp:/tmp

  auth-db:
    build: ./auth-db/postgresql
    container_name: auth-db
    restart: always
    tty: true
    ports:
      - 54320:5432
    volumes:
      - ./auth-db/dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - common-network 
